export const FKNconstants = {
    appName:'FKN',
    appTitle:'Vendas Externas',
    appFullTitle:'FKN Vendas Externas',
    register:'REGISTRAR',
    permissionPhonecall:'Permissão necessãria para verificar a liberação do celular para acesso ao aplicativo.',
    confirm:'CONFIRMAR',
    registerLable1:'Informe um nome para seu dispositivo',
    registerLabel2:'Informe a chave para autenticação',
    userName:'usuário',
    password:'senha',
    access:'ACESSAR',
    loginPageTitle:'Força de Vendas FKN',
    verify:'VERIFICAR',
    verifyDescription:'Aguardando aprovação, contate o administrador do sistema para liberação do dispositivo',
    copyRight1:'Copyright © 2016 FKN Informática.',
    copyRight2:'Todos os direitos reservados.',
    registerRequired:'Favor preencher o chave!',
    alertLoginTitle:'Mensagem',
    alertLoginMessage:'Campo(s) obrigatorios em branco!',

    // Drawer Items
    inicio:'Início',
    cliente:'Cliente',
    prospeccao:'Prospecção',
    produto:'Produto',
    pedido:'Pedido',
    duplicatas:'Duplicatas',
    agenda:'Agenda',
    ordem:'Ordem',
    relatorios:'Relatórios',
    section1:'Sincronização',
    sincronizar:'Sincronizar',
    configuraccao:'Configuração',
    section2:'Suporte',
    suporte:'Suporte',
    sobre:'Sobre',
    sair:'Sair'
    
}