import { Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');
const COLORS = {
    WHITE: 'white',
    BLACK: '#000000',
    GREY: '#898989',
    THEME: '#349e37',
    PRIMARY: '#349e37',
    INFO: '#1232FF',
    ERROR: '#FE2472',
    WARNING: '#FF9C09',
    SUCCESS: '#45DF31',
    TRANSPARENT: 'transparent',
    INPUT: '#808080',
    DEREGISTER_RED: 'rgb(219, 31, 38)',
    PLACEHOLDER: '#9FA5AA',
    NAVBAR: '#F9F9F9',
    BLOCK: '#808080',
    MUTED: '#9FA5AA',
    NEUTRAL: 'rgba(255,255,255, 0.65)',
    FACEBOOK: '#3B5998',
    TWITTER: '#5BC0DE',
    DRIBBBLE: '#EA4C89',
    ICON: '#000000',
    COLOR_PRIMARY: '#4CAF50',
    COLOR_PRIMARYDARK: '#00574B',
    COLOR_ACCENT: '#ABABAB',
    GRAY: '#F0F4F2',
    DARK_GRAY: '#BDBDBD',
    GRAY_NEW: '#E3DDE6',
    VERY_DARK_GRAY: '#9E9E9E',
    PROFILE_BLUE: '#8B9BFB',
    HEALTH_ACCESS_RED_LIGHT: '#E3768E',
    HEALTH_ACCESS_RED_DARK: '#EF5350',
    DARK_GREY: '#BDBDBD',
    NAVIGATION_BG: '#222840',
    NAVIGATION_DIVIDER: '#252B43',
    GREEN_DARK: '#44AF5A',
    GREEN_LIGHT: '#54C39B',
    PURPLE_DARK: '#8B9DF7',
    PURPLE_LIGHT: '#C7A8F7',
    BLUE_DARK: '#1ABEB4',
    BLUE_LIGHT: '#75C2F0',
    FITBIT_BLUE: '#00B0B8',
    NEW_COLOUR: '#E23838',
    SKY_BLUE: '#007AFF',
    BLUE: '#0D2846',
    ORANGE_DARK: '#EF8445',
    ORANGE_LIGHT: '#F5C184',
    DISABLED_COLOR: '#DDDDDD',
    BLACK_OPACITY: 'rgba(0, 0, 0, 0.70)',
    CALORIE_LIGHT: '#e5a1d2',
    CALORIE_DARK: '#8a73bf',
    POOR_HEALTH_SCORE: '#f77049',
    AVERAGE_HEALTH_SCORE: '#ab90f3',
    GOOD_HEALTH_SCORE: '#f4bd0e',
    AWESOME_HEALTH_SCORE: '#3db54b',
    BACKGROUND_BLACK: '#1a1a1e',

    NEW_GREEN: 'rgb(37, 221, 118)',
    PIN_GREEN: 'rgb(124, 252, 39)',
    NEW_BLUE: 'rgb(67, 145, 247)',
    NEW_ORANGE: 'rgb(253, 159, 19)',
    NEW_PINK: 'rgb(247, 42, 255)',
    NEW_ERROR_RED: 'rgb(251, 0, 64)',
    MNEMONIC_BG: '#19191c',

    OPTION_SELECT_TEXT: '#E289D6',
    OPTION_DISABLED_TEXT: '#B550A8',
    QUESTION_HEADER_TEXT: '#978FFF',
    GREEN_QUESTION_HEADER: '#3ABDF9',
    GREEN_OPTION_TEXT: '#59F6FF',
    GREEN_OPTION_DISABELD: '#298F8E',
    PINK_QUESTION_HEADER: '#FD64C6',
    PINK_OPTION_TEXT: '#B381F1',
    PINK_OPTION_DISABLED: '#9240EF',
    PURPLE_QUESTION_HEADER: '#8D99F5',
    PURPLE_OPTION_TEXT: '#E0AAFF',
    PURPLE_OPTION_DISABLED: '#A85CDF',
    PURPLE_OPTION_FADED: 'rgb(58, 27, 82)',
    YELLOW_QUESTON_HEADER: '#36E8FD',
    YELLOW_OPTION_TEXT: '#28C0FF',
    YELLOW_OPTION_DISABLED: '#0392D6',
    SLIDER_GREEN_TEXT: '#96EEA3',
    SLIDER_YELLOW_TEXT: '#E6E38F',

    ABOUT_US_PINK: '#E45EBB',
    DASHBOARD_GREEN: '#1BE089',
    SIDE_MENU_GRAY: '#45464C',
    WEARABLE_HEADER_TEXT: '#BE65FF',
    WEARABLE_OPTION_TEXT: '#28E1FF',
    WEARBALE_DISABLED_TEXT: '#0290D4',

    LIGHT_GRAY: '#717687',
    BLACK_LIGHT: 'rgb(27, 27, 32)',
    DAHBOARD_CALORIE_TEXT: '#FB3362',
    WHITE_OPACITY: 'rgba(255, 255, 255, 0.3)',

    REWARD_SCORE_TEXT: '#FFE282',
    REWARD_DAILY_SCORE_TEXT: '#B4E2FF',
    FAQ_QUESTIONS_COLOR: '#35A2FF',
    MEDICAL_INFO_COLOR: '#FC4849',
    BUTTON_BG: '#398F5A'
};
const FONTFAMILY = {
    BLACK: 'Outfit-Black',
    BOLD: 'Outfit-Bold',
    EXTRA_BOLD: 'Outfit-ExtraBold',
    EXTRA_LIGHT: 'Outfit-ExtraLight',
    ITALIC: 'Outfit-Italic',
    LIGHT: 'Outfit-Light',
    MEDIUM: 'Outfit-Medium',
    REGULAR: 'Outfit-Regular',
    SEMI_BOLD: 'Outfit-SemiBold',
    THIN: 'Outfit-Thin',
};

const guidelineBaseWidth = 375;
const guidelineBaseHeight = 812;

const horizontalScale = (size: number) => (width / guidelineBaseWidth) * size;
const verticalScale = (size: number) => (height / guidelineBaseHeight) * size;
const moderateScale = (size: number, factor = 0.5) => size + (horizontalScale(size) - size) * factor;
const SIZES = {
    EXTRA_LARGE: moderateScale(24),
    LARGE: moderateScale(18),
    BASE: moderateScale(16),
    FONT: moderateScale(16),
    OPACITY: 0.6,
    MEDIUM: moderateScale(14),
    SAMLL: moderateScale(12),
    BORDER_RADIUS: moderateScale(4),
    BORDER_WIDTH: moderateScale(0.8)
};
export default {
    COLORS,
    SIZES,
    FONTFAMILY,
    horizontalScale, verticalScale, moderateScale
};